### ISSUE TITLE
Syntax for CudaText/Synwrite

### ISSUE THREAD

**Issue by Alexey-T** [redskyit/ScriptDriver#18]
Seems its easy to make syntax, since lang is simple, don't you need syntax?

**Comment by Mehuge** [comment]
If you mean, does ScriptDriver need some syntax rules, then probably.  

Does it have any rules? Yes, they are loosely described here https://github.com/redskyit/ScriptDriver/wiki/Language-Syntax-(v0.3)

**Comment by Alexey-T** [comment]
okay. Do you have many users? i can make syntax for Cudatext then...

**Comment by Mehuge** [comment]
No :) afaik, only me!
